// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gclywtgbyfefsbcjektn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjbHl3dGdieWZlZnNiY2pla3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMDc5ODgsImV4cCI6MjA1MDY4Mzk4OH0.7C93gkSj-TdSG-moYTBYAVL0PiangeKa7B5y5leTE7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);